# task cli documentation
# https://taskfile.dev/usage/
# https://taskfile.dev/styleguide/

version: "3"

env:
    LOG_LEVEL:
        sh: echo "${LOG_LEVEL:-DEBUG}"

tasks:
    # poetry cli documentation
    # https://python-poetry.org/docs/cli/

    install:
        aliases: [i]
        desc: Installs the project dependencies via poetry install
        cmds:
            - poetry install --no-root
            - poetry lock 
            - poetry sync --no-root

    fmt:
        aliases: [f]
        desc: Format with isort & black via poetry
        cmds:
            # https://pycqa.github.io/isort/
            - poetry run isort .
            # https://black.readthedocs.io/
            - poetry run black .

    lint:
        aliases: [l]
        desc: Run pylint via poetry
        cmds:
            # https://pylint.readthedocs.io/
            - poetry run pylint . --recursive=y

    # test:
    #     aliases: [t]
    #     desc: Run tests & coverage via poetry
    #     cmds:
    #         # https://docs.pytest.org/
    #         - poetry run pytest {{.CLI_ARGS}}


    build:
        aliases: [b]
        desc: Build artifact.zip package for deployment via poetry
        cmds:
            - rm -rf dist
            - rm -rf build
            - poetry build
            - poetry run pip install --no-cache-dir -t build/package dist/*.whl
            - poetry run pyclean build/package
            - cd build/package ; zip -r ../artifact.zip .


    all:
        aliases: [a]
        desc: Run all tasks in order
        cmds:
            - task: install
            - task: fmt
            - task: lint
            #- task: test
